DEFAULT_LAYOUT = [
    {"id": "purchase_order", "type": "document", "title": "Purchase Order", "col": 2},
    {"id": "purchase_invoice", "type": "document", "title": "Purchase Invoice", "col": 2},
    {"id": "payment_request", "type": "document", "title": "Payment Request", "col": 2},
    {"id": "sales_order", "type": "document", "title": "Sales Order", "col": 2},
    {"id": "sales_invoice", "type": "document", "title": "Sales Invoice", "col": 2},
    {"id": "journal_entry", "type": "document", "title": "Voucher Entry", "col": 2},
    {"id": "suppliers", "type": "master", "title": "Suppliers", "col": 2},
    {"id": "customers", "type": "master", "title": "Customers", "col": 2},
    {"id": "employees", "type": "master", "title": "Employees", "col": 2},
    {"id": "payables", "type": "amount", "title": "Payables", "col": 2},
    {"id": "receivables", "type": "amount", "title": "Receivables", "col": 2},
    {"id": "income_expense", "type": "income_expense", "title": "Income & Expenses", "col": 6},
    {"id": "payables_ageing", "type": "ageing", "title": "Payables Ageing", "col": 3},
    {"id": "receivables_ageing", "type": "ageing", "title": "Receivables Ageing", "col": 3},
    {"id": "monthly_trend", "type": "monthly_trend", "title": "Monthly Trend", "col": 4},
    {"id": "top_suppliers", "type": "ranking", "title": "Top 5 Suppliers", "col": 3},
    {"id": "top_customers", "type": "ranking", "title": "Top 5 Customers", "col": 3},
    {"id": "document_status_summary", "type": "document_status", "title": "Document Status Summary", "col": 2},
    {"id": "recent_activities", "type": "recent_activities", "title": "Recent Activities", "col": 4},
    {"id": "cash_position", "type": "cash_position", "title": "Cash Position", "col": 3},
    {"id": "expenses_by_category", "type": "expenses_by_category", "title": "Expenses by Category", "col": 3},
    {"id": "quick_shortcuts", "type": "shortcuts", "title": "Quick Shortcuts", "col": 2},
]

WIDGET_CATALOG = [
    {"id": "purchase_order", "type": "document", "title": "Purchase Order", "col": 2},
    {"id": "purchase_invoice", "type": "document", "title": "Purchase Invoice", "col": 2},
    {"id": "payment_request", "type": "document", "title": "Payment Request", "col": 2},
    {"id": "sales_order", "type": "document", "title": "Sales Order", "col": 2},
    {"id": "sales_invoice", "type": "document", "title": "Sales Invoice", "col": 2},
    {"id": "journal_entry", "type": "document", "title": "Voucher Entry", "col": 2},
    {"id": "suppliers", "type": "master", "title": "Suppliers", "col": 2},
    {"id": "customers", "type": "master", "title": "Customers", "col": 2},
    {"id": "employees", "type": "master", "title": "Employees", "col": 2},
    {"id": "payables", "type": "amount", "title": "Payables", "col": 2},
    {"id": "receivables", "type": "amount", "title": "Receivables", "col": 2},
    {"id": "income_expense", "type": "income_expense", "title": "Income & Expenses", "col": 6},
    {"id": "payables_ageing", "type": "ageing", "title": "Payables Ageing", "col": 3},
    {"id": "receivables_ageing", "type": "ageing", "title": "Receivables Ageing", "col": 3},
    {"id": "monthly_trend", "type": "monthly_trend", "title": "Monthly Trend", "col": 4},
    {"id": "top_suppliers", "type": "ranking", "title": "Top 5 Suppliers", "col": 3},
    {"id": "top_customers", "type": "ranking", "title": "Top 5 Customers", "col": 3},
    {"id": "document_status_summary", "type": "document_status", "title": "Document Status Summary", "col": 2},
    {"id": "recent_activities", "type": "recent_activities", "title": "Recent Activities", "col": 4},
    {"id": "cash_position", "type": "cash_position", "title": "Cash Position", "col": 3},
    {"id": "expenses_by_category", "type": "expenses_by_category", "title": "Expenses by Category", "col": 3},
    {"id": "quick_shortcuts", "type": "shortcuts", "title": "Quick Shortcuts", "col": 2},
    {"id": "stock_snapshot", "type": "snapshot", "title": "Stock Snapshot", "col": 3},
    {"id": "manufacturing_snapshot", "type": "snapshot", "title": "Manufacturing Snapshot", "col": 3},
    {"id": "crm_snapshot", "type": "snapshot", "title": "CRM Snapshot", "col": 3},
    {"id": "asset_snapshot", "type": "snapshot", "title": "Asset Snapshot", "col": 3},
]
